version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: yaur
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://root:pass@postgres:5432/yaur
    depends_on:
      - postgres


