version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: yaur
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
